name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-22"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDU4YzZlY2ItNzcyNC00M2JlLThiMzgtY2FmNDc5MzIwMDFlIiwidGVuYW50X2lkIjoiMzk4MGQ4NGY0ZmY4MmM3MDAyMDIzMWZmYWY5YzdlMDc3NGZlNjE4YmIxNTRlNTFiYzg4YWU3ODRiNjNmYjg4MyIsImludGVybmFsX3NlY3JldCI6IjY0ZTAxMTk4LWNkNTMtNDBhMy05ZDQ1LThjZmM3MDc5MDU1MCJ9.unhoWXHBgmYpWBgBNwvcANhJHXgzCm0duHhHdAo8lvE"
JWT_SECRET = "asdasdasd"